import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from '../components/Navigation';
import Footer from '../components/Footer';
import Main from '../components/Main';
import NavItem from '../components/NavItem';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navItems = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation>{navItems.map( (navItem, i) => (<NavItem key={`nav_item_${i}`} {...navItem}/>) )}</Navigation>
        <Main>{children}</Main>
        <Footer/>
      </body>
    </html>
  )
}
